use given levels without taking abs
datavisyn/chartjs-plugin-error-bars pull request #6
Opened 2019-02-02 12:41 UTC by jli05

When the error levels are directly specified, use them as given without taking `abs`.

2019-02-20 16:44 UTC, sluger requested changes
hi @jli05, 

thanks for the PR, I think your changes would be a nice addition to the plugin. 

However, I would like you to take care of a few things first:
- Eslint conformity. please run `npm run test` to see the problems.
  - you can add the `console.assert` statement to the `.eslintrc`, thats fine.
  - use triple equal signs and do not use coercion if possible.
  - add curly bracers for single conditional statements or just use the `if a ? true : false` notation
- use `Array.isArray()` instead of `instanceof`

As for the changed data structure of the errorBars config property. I think it would be more flexible if you would change it to an Array of elements of type `{plus: <number>, minus: <number>}`. Then you could specify the start and end for each individual bar. With the current approach, i am not sure how the start and end points for the multiple errorbars are computed. It seems a bit magic.

With the proposed changed, your given example with absolute values:
```
'Value': [20, 40, 60, 80],
```
would look like the following:
```
'Value': [{plus: 80, minus: 20}, {plus: 60, minus: 40}],
```

Cheers 
Stefan

2019-02-28 16:50 UTC, jli05 commented
Hello I retracted one commit now there remains only a simple one. It passes the `npm run test`. May we merge?

2019-02-28 17:10 UTC, jli05 commented
Regarding the design to plot multi-bars, actually I was trying to implement the "graded error bars" in Chapter 16 of [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/visualizing-uncertainty.html), or even most broadly, the case when we have *n* quantiles (*n*=1,2,3,...).

How shall we design an API for the most broad use case?

2019-03-06 17:55 UTC, jli05 commented
Could we merge this one?

Any thoughts about the most general design (cf: last comment)?

2019-03-13 08:49 UTC, sgratzl commented
Hi,
I created an adapted version in https://github.com/datavisyn/chartjs-plugin-error-bars/pull/7 which should be merged soon. It uses the suggested changed datastructure but incorporates your suggested changes for multiple error bars, line width, and options.

2019-03-14 09:40 UTC, sgratzl commented
closing in favor of #7

2019-03-14 09:40 UTC, closed without merging